### ISSUE TITLE
No GDExtension library found

### ISSUE THREAD

**Issue by tensorFan** [Johnnoe2618/large-linear-algebra#1]
Hey! I tried to add your addon to my project on my linux operating system. I managed to compile and link the files using scons, and got a library file liblargelinearalgebra.linux.template_release.x86_64.so which I added to the largelinearalgebra.gdextension file like so: 
[configuration]
entry_symbol = "largelinearalgebra_library_init"
compatibility_minimum = 4.1

[libraries]
linux.release.x86_64 = "res://addons/largelinearalgebra/bin/liblargelinearalgebra.linux.template_release.x86_64.so"
windows.debug.x86_64 = "res://addons/largelinearalgebra/bin/largelinearalgebra.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://addons/largelinearalgebra/bin/largelinearalgebra.windows.template_release.x86_64.dll"

However upon then opening my project I get this error:
![image](https://github.com/Johnnoe2618/large-linear-algebra/assets/62095373/bb7f25ca-dde9-42d5-85c9-9f5c9db5660b)

Do you know what could be wrong?

**Comment by Johnnoe2618** [comment]
Hey!

Have you tried adding:
linux.**debug**.x86_64 = "res://addons/largelinearalgebra/bin/liblargelinearalgebra.linux.template_release.x86_64.so"
?
I noticed that in my project, on windows, that when run from the editor, it does not work when I delete the 'debug' line from the .gdextension file. But, when I add the 'debug' line back in, but pointing to the template_release dll rather than the template_debug, it still works, so you won't have to recompile if you don't want to, just add the extra line in.

If that doesn't work, it might be a good idea to try, just compiling for debug mode. In any case, for debugging purposes, I've put in a little logging for basic mistakes and errors, that don't compile in the release version, so if you want to be safe, you might want to compile for the debug version anyway.

**Comment by tensorFan** [comment]
Wow I never would have thought of that myself, such an obscure solution compared to the error message! Thank you. I had to upgrade my version of Godot for archlinux from 4.1.2 to 4.1.3 but now there are no errors!
